version: "3"

services:
  eludris:
    container_name: eludris
    env_file: .env
    restart: unless-stopped

    environment:
      - DATABASE_URL=mysql://root:root@mariadb/eludris
      - REDIS_URL=redis://redis/1

    ports:
      - "8000:8000"
      - "9000:9000"

    build:
      context: .
      dockerfile: Dockerfile

  mariadb:
      image: mariadb:latest

      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ROOT_HOST=%
        - MYSQL_DATABASE=eludris

      volumes:
        - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: "redis:alpine"

    command: redis-server

    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
